import "./globals.css";

export const metadata = {
  title: "Jonathan Word Dev Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-zinc-900 via-zinc-950 to-gray-900">
        {children}
      </body>
    </html>
  );
}
